version: '3.8'

services:
  api:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/books
      - REDIS_URL=redis://redis:6379
      - REDIS_TTL=3600
      - CORS_ORIGIN=*
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=100
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
